---
# This playbook is used to set up a machine for ansible.
- hosts: all
  become: true
  vars_files:
    - vars/vars.yml
    - vars/vault.yml
    - vars/dock_mosquitto.yml
#  roles:
#    - sshdconfig
  tasks:  
# install docker
  - name: install docker and docker-compose
    apt:
      name:
        - docker.io
        - docker-compose
      state: latest
      update_cache: yes
    when: ansible_distribution in  ["Debian", "Ubuntu"]

  - name: Add user to docker group
    user:
      name: rick
      groups: docker
      append: yes
      state: present

# set up folders
  - name: Create docker directory structure
    become: yes
    become_user: rick
    file:
      path: /home/rick/docker/share
      state: directory
    tags: docker
    
  - name: Create mosquitto directory structure
    become: yes
    become_user: rick
    file:
      path: /home/rick/docker/{{ item }}
      state: directory
    loop:
      - mosquitto/config
      - mosquitto/data
      - mosquitto/log

# create mosquitto config file
  - name: add sudoers file for simone
    copy:
      src: mosquitto.conf
      dest: /home/rick/docker/mosquitto/config
      owner: rick
      group: rick
      mode: 0644

# create docker compose
  - name: Setting up docker-compose
    include_role:
      name: docker_compose_gen
    vars:
      docker_compose_generator_output_path: '/home/rick/docker'
      docker_compose_generator_uid: rick
      docker_compose_generator_gid: rick
# launch mqtt
...